title: My Awesome Docs
description: Documentation for My Project
theme: jekyll-theme-cayman  # or any other built-in theme
# These will appear in the browser tab
url: https://NomadRedPanda.github.io
baseurl: "/notes"  # Don't forget the leading slash!

# Add a navigation bar (if your theme supports it)
nav:
  - Home: README.md
  - Git: docs/git.md
  - Cline: docs/cline.md